platform :ios, '13.0'
target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'BackServices', :git => "https://github.com/JosPerez/BackServices.git", :branch => "main"

end
